### ISSUE TITLE
Feature: User can sign-up

### ISSUE THREAD

**Issue by tghaffari** [tghaffari/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign-up

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to sign-up for an account. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-13 at 11 05 02 AM](https://user-images.githubusercontent.com/106884008/189977338-e0dc3c99-e973-4aab-b6b4-aaf991726253.png)
![Screen Shot 2022-09-13 at 11 06 05 AM](https://user-images.githubusercontent.com/106884008/189977485-9b858534-3a9f-4cf7-b3cd-2d15eec6d78a.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to include a post request for sign-up 
  - [x]  User argon2 to hash the users inputted password and save that password and username to the database  
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to handle sign-up
  - [x] Store the user's input in state. 
  - [x] Check that the password meets the password requirements and update the form accordingly 
  - [x] Send a request to the database to make sure that the user's selected username doesn't already exist. If it does, send a message to the user to create a new one. 
  - [x] If the username and password are valid, allow the user to click submit 
  - [x] On submit, send a request to the backend that stores the new user's log-in information. 
- [x] Update app component to render the sign-up page with the correct hash-routing

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
