### ISSUE TITLE
Feature: User can edit their book entries 

### ISSUE THREAD

**Issue by tghaffari** [tghaffari/final-project#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit their book entries 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can edit their entries to change any of the form fields or move it to a different shelf

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-13 at 11 32 18 AM](https://user-images.githubusercontent.com/106884008/189982516-123c50b6-71f8-4a5b-b8d5-0684b54279c3.png)

![Screen Shot 2022-09-13 at 11 32 28 AM](https://user-images.githubusercontent.com/106884008/189982528-fadb83d1-c4fe-49ed-9ec2-9f887a34c8a7.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [ ] Update `server/index.js` to 
  - [ ]  Add a put request to update the book details using the book id and user id in the library table 
  - [ ] include error handling to ensure that a valid id number is included as well as the required fields. 
  - [ ] Update the quote -- check first to see if a quote exists. If not, save it as save it as a new quote. If it does, update it using the bookid and user id
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Update my-books component 
   - [ ] Add a pencil icon for the user to click on and add an event listener for the pencil icon 
   - [ ] Create a function for when the pencil is clicked on to render the book-entry-details component (modal)
   - [ ] In that same function, get the book details for the associated book and store it in a variable and use it to pre-populate the form 
- [ ] Updated book-entry-details component 
  - [ ] Display an update button instead of the save button 
  - [ ] When the user clicks the update button, send a put request to the server to update the book details. 

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
