### ISSUE TITLE
Feature: User can see the home page

### ISSUE THREAD

**Issue by tghaffari** [tghaffari/final-project#14]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the home page

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can navigate to the home page to see their most recently saved books

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="184" alt="Screen Shot 2022-09-16 at 11 07 42 AM" src="https://user-images.githubusercontent.com/106884008/190704329-66a05c75-6860-41cd-9481-b25574b5e2e6.png">
<img width="599" alt="Screen Shot 2022-09-16 at 11 08 14 AM" src="https://user-images.githubusercontent.com/106884008/190704336-99b6b4b1-ecd2-45bc-8243-3006f22893b9.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to accept a get request that returns the 5 latest books added with a completed date and the 5 latest books added where completed date is null
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component (page) to show the home page 
     - [x] Send a fetch request to the server to get the user's latest 5 books added to each bookshelf type. 
     - [x] If there are no books saved, make a text placeholder encouraging the user to add more books 
    - [x] Mobile view will show the latest three books (hide the last two books by using overflow)
    - [x] Desktop view will the latest five books 
    - [x] Set up hash routing so when the user clicks on one of the bookshelf names, they're re-routed back to their library page
- [x] Update app.jsx to route you to the home page when you click on the home icon.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
