### ISSUE TITLE
Feature: User can log-in

### ISSUE THREAD

**Issue by tghaffari** [tghaffari/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can log-in

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can log-in to their account. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-13 at 11 07 23 AM](https://user-images.githubusercontent.com/106884008/189977713-23e12e97-22c0-48ac-8aa4-aadfe073305d.png)
![Screen Shot 2022-09-13 at 11 07 48 AM](https://user-images.githubusercontent.com/106884008/189977778-0d9d2802-4fb8-4ac9-a16a-88c15e0013df.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks
- [x] Create an authorization middleware that pulls the userId of the signed token
- [x] Update `server/index.js` to accept a post request for sign-in 
  - [x] Make username and password required and send an error message if missing 
  - [x] Send a request to the database to retrieve the userId and hashed password using the inputted username. 
  - [x] Verify that the password is correct. If it isn't, send an error message to the user. 
  - [x] If the password is correct, get a token (update token secret in env file).  
 

- [x] Update post request for saving books 
  - [x] Update the second db request to save the book to the userId for the user that's signed in 
  

- [x]  Update get request for getting all books 
  - [x] Update the where clause to retrieve the books of the signed-in user 
  - [x] Pass userId as a param
  

- [x] Update get request for recent books 
  - [x] Update userIds in both where clauses to retrieve the books of the signed-in user 
  - [x] Pass userId as a param  

- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update app.jsx 
  - [x] Updated renderPage method to handle hash-routing for sign-in
  - [x] Create a method that handles sign-in. Using the token and userId from the database query, save the token in local storage and update the user stored in state 
  - [x] Update app.jsx ComponentDidMount to retrieve the token from local storage(if there is one) and identify the user (if already logged in). Updated the value of user stored in state accordingly. 
  - [x] Update contextValue to also store the sign in method
 

- [x] Update auth.jsx
  - [x] Updated welcome message to show the appropriate message for "sign-in"
  - [x] Update the props for AuthForm to include the path and the sign-in method 
  

- [x] Update auth-form.jsx
  - [x] Update components to reflect sign-up page when the route is "sign-in"
  - [x] Update on submit handler to change hash to sign-in when the sign-up form is submitted
  - [x] Update onSubmit handle to call the sign-in method when on the sign-in page
  

- [x] Update auth-background.jsx 
  - [x] if there's a user, return null 

- [x]   Update search-results.jsx 
  - [x] Update saveBook method to send the token(stored in local storage) as a parameter in the header of the fetch request.  
  

- [x] Update my-books.jsx 
  - [x] Update componentDidMount to include token in fetch request in the header
  

- [x] Update home.jsx 
  - [x] Update getRecentBooks method to pass the token of the signed in user  in the header of the fetch request.  
 

### 🧑‍⚕️ Clean Up Tasks
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
