### ISSUE TITLE
Feature: User can sign-out 

### ISSUE THREAD

**Issue by tghaffari** [tghaffari/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign-out 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can sign-out of their account. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-13 at 11 10 37 AM](https://user-images.githubusercontent.com/106884008/189978315-ff438d50-5126-44bc-9cf1-f53951d0dd85.png)
![Screen Shot 2022-09-13 at 11 10 57 AM](https://user-images.githubusercontent.com/106884008/189978403-7e073d18-97c3-4be1-857d-96a00d26b06d.png)
![Screen Shot 2022-09-13 at 11 11 15 AM](https://user-images.githubusercontent.com/106884008/189978500-b425921b-6c55-468c-a00f-79af641e088e.png)
![Screen Shot 2022-09-13 at 11 11 22 AM](https://user-images.githubusercontent.com/106884008/189978497-a8e5df53-ffb5-4af4-94e6-8787293b57a5.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update app.jsx
  - [x]  Add a handleSignOut method that removes the token from local storage and sets user back to null
  - [x] Add this method to context
  
- [x] Update navbar component
  - [x] Add a sign-out button for desktop and mobile
  - [x] Add an onClick event listener for the sign-out button with the handleSignOut method from app.jsx as the callback function. 

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
