### ISSUE TITLE
Feature: User can search for books 

### ISSUE THREAD

**Issue by tghaffari** [tghaffari/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for books 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can search for books that they may want to add to their library and view search results. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-13 at 11 13 01 AM](https://user-images.githubusercontent.com/106884008/189978849-4660e0f4-baaf-48d0-8c1b-6b9b97bc606f.png)
![Screen Shot 2022-09-13 at 11 13 41 AM](https://user-images.githubusercontent.com/106884008/189978987-994d6060-8627-4992-8fa1-a3d278b5523c.png)
![Screen Shot 2022-09-13 at 11 13 47 AM](https://user-images.githubusercontent.com/106884008/189979003-ad64dd46-1d82-4e51-b71c-a085ef69a9a8.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a parse route file to handle route changes and get the route in the desired format. 

- [x] Create a page-container component to set up the container for the page, excluding the navbar

- [x] Create a component to create the navbar
  - [x] For mobile, render two navbars on the top with the search button, app name, and sign out button on the top one. And the home button on the bottom one. 
  - [x] For desktop, there's just one navbar at the top with all the icons and navigation links. 

   - [x]  Create a click event handler for the search bar. When clicked, the search bar replaces the bottom navbar on mobile. For desktop, it replaces the search icon.  
  - [x] Use an onChange event listener to re-render the page every time something is typed into the search bar and update the value of what's being searched 
  - [x] Listen for a "submit" event and change the hash to redirect the user to the search page. The hash should contain the search parameters in the query string.
 
- [x] Create a component to render the search results and show the search results page
  - [x] Use the hash to obtain the search parameters and send a request to the api to obtain the search results. Change the view to the search results page. 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
