### ISSUE TITLE
Feature:  User can save books to their read bookshelf or want to read bookshelf.

### ISSUE THREAD

**Issue by tghaffari** [tghaffari/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save books to their to-read bookshelf

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can keep track of what books they want to read. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-13 at 11 16 11 AM](https://user-images.githubusercontent.com/106884008/189979385-a68224fa-82b4-4ac0-9933-40ef8b5e3c22.png)
![Screen Shot 2022-09-13 at 11 16 35 AM](https://user-images.githubusercontent.com/106884008/189979476-bef1c7e5-a862-4062-8b6f-0b7e14248f8e.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks
- [x] Update `schema.sql` to create database according to schema obtained from db designer
- [x] Update `data.sql` to import a guest user into the database 

### ☁️ Server Tasks

- [x] Update `server/index.js` to accept a post request to add books to the database and add a book to a users library in the database
  - [x]  Add book information to the books table in the database 
  - [x]  Add required information to the library table 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update search-results component to add an id  to each li element that matches the index of the search result. 
  - [x]  Use that index to find the book's information from where it's being stored in order to save it if selected by the user. 
- [x] Update search-results component to  show a button that allows the user to add a book to their library 
   - [x]  When the user clicks on the button, a dropdown of options appears to allow the user to add their book to their  to-read bookshelf. 
   - [x] Use an event-listener on the button so if the user selects to-read, the book is automatically added to their library.
   - [x] Use fetch to send a post request to the server to save the book to the user's to-read bookshelf

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
