### ISSUE TITLE
Feature: User can aadd a book to their read bookshelf by adding the completed date

### ISSUE THREAD

**Issue by tghaffari** [tghaffari/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add the date that they finished the book

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user has finished reading a book, they can enter when they finished it. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-13 at 11 19 25 AM](https://user-images.githubusercontent.com/106884008/189980015-275d7bba-e7be-45ba-ada3-76edbbd70ec6.png)
![Screen Shot 2022-09-13 at 11 18 56 AM](https://user-images.githubusercontent.com/106884008/189980019-140c393e-2c97-40c4-91b9-68daf8038c33.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to  accept a completed date parameter in the post request when saving a book
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update search results component and add a a new option to the "add to library" select button- "READ"
- [x] Update search results component and add a a new conditional to the "add to library" select button onChange event listener callback function
  - [x] If the user selects "to-read", the information is automatically sent to the database. 
  - [x] If the user selects "read", pass the book information as a prop to the modal and continue the process of saving the entry in the modal. 
- [x] Create a component to  display the modal if a user is adding a book to their read library 
    - [x] Create a form field that verifies which bookshelf the book is being added to. If the user selects to-read, don't allow them to fill out the date completed field. 
    - [x] If the user selects read, make the completed date a required form field. 
    - [x] Add a submit event listener and have it send the saved information from the form to the database in it's callback function. 

### 🧑‍⚕️ Clean Up Tasks
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
