### ISSUE TITLE
Feature: User can save a quote from the finished  book. 

### ISSUE THREAD

**Issue by tghaffari** [tghaffari/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save a quote from the finished  book. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user had a favorite quote, they can save it for later viewing. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-13 at 11 21 06 AM](https://user-images.githubusercontent.com/106884008/189980388-d465100d-9a7b-4ce3-82d3-201a0edbf7ba.png)
![Screen Shot 2022-09-13 at 11 21 15 AM](https://user-images.githubusercontent.com/106884008/189980411-0769d892-4300-4c43-ad9d-456c05420878.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` 
     - [x]  Update saveBooks post request to save the user's inputted quote and page number (if included)
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update book-entry-details component to
  - [x]  Include a form field to allow the user to enter a quote 
  - [x] Include a form field to allow the user to enter associated page number(s)
  - [x] make page numbers necessary if quote is entered 
  - [x] Update the handle submit function to save the quote to the database (update fetch request)

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
