### ISSUE TITLE
Feature: User can view their library 

### ISSUE THREAD

**Issue by tghaffari** [tghaffari/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their library 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can see all the books that they have saved to their library. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-13 at 11 22 38 AM](https://user-images.githubusercontent.com/106884008/189980653-d875f037-9eec-4ee5-ae99-cde1d651f8b0.png)
![Screen Shot 2022-09-13 at 11 22 30 AM](https://user-images.githubusercontent.com/106884008/189980656-21fa86b1-aec9-4050-900a-1fa24ff074f4.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to accept a get request to grab the user's saved library books from the database.
  - [x] Use the books table and library table to send the appropriate information 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component (page) to display the user's save books 
   - [x] Send a fetch request to the database to get the books 
   - [x] Display the returned books to the user
   - [x] Set up media queries for desktop and mobile

- [x] Update navbar component to show a link to navigate to the "my Books" page 
  - [x] add a click event listener to the link to change the hash so the user will be be navigated to the "My Books page"
 
- [x]  Update app.jsx to handle the hashchange and render the "My Books" page when the hashchange occurs.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
