### ISSUE TITLE
Feature: User can view all saved quotes 

### ISSUE THREAD

**Issue by tghaffari** [tghaffari/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view all saved quotes 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can go back and look at all the quotes that they saved. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-13 at 11 28 40 AM](https://user-images.githubusercontent.com/106884008/189981809-bca05652-2897-43dc-882d-5c1498736a7f.png)

![Screen Shot 2022-09-13 at 11 28 50 AM](https://user-images.githubusercontent.com/106884008/189981801-75442b58-3d42-48f3-b032-bba9c8507616.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to send a get request to select the quotes, page number and associated book details (author, title) from the database. Quote and page number come from the quotes table and book details come from the books table. Get all the information needed using a join sql statement. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to display the user's quotes 
  - [x] Send a fetch request to the server to obtain the quotes 
  - [x] set up an error message if unable to retrieve information from the database 
  - [x] Make a function to properly format the quote, book title, author, and page number(s)
  - [x] In the render function, redirect the user to the sign-in page if there's no user signed in. 
  - [x] import app.context
  - [x] Add placeholder text if no books are saved.
 
- [x] Update navbar component to 
  - [x] Include a quotes link for mobile 
  - [x] include a view quotes link for desktop 
  - [x] Make the a link redirect the user to the quotes pages 

- [ ] Update app.jsx to include hash routing for viewing quotes 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
